create TABLE client(
ID_DEP_CLIENT VARCHAR(100) PRIMARY KEY,
NAME_CLIENT VARCHAR(100)
);

create TABLE project(
 id SERIAL PRIMARY KEY,
 id_current_project INT,
 ID_DEP_CLIENT VARCHAR(100),
 ID_PROJECT VARCHAR(100),
 FOREIGN KEY(ID_DEP_CLIENT) REFERENCES client (ID_DEP_CLIENT)
)
